local inline = require('rowan.inline')

local function buffer(line, col)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, { line })
  vim.api.nvim_win_set_cursor(0, { 1, col })
end

local function line()
  return vim.api.nvim_get_current_line()
end

-- Selects `chars` characters starting at 0-based byte column `col`, then toggles.
local function toggle_selection(kind, col, chars)
  vim.api.nvim_win_set_cursor(0, { 1, col })
  vim.cmd('normal! v' .. (chars > 1 and (chars - 1) .. 'l' or ''))
  inline.toggle(kind)
end

describe('inline.toggle in normal mode', function()
  it('wraps and unwraps the word under the cursor', function()
    buffer('this is probably fine', 9)
    inline.toggle('soft')
    assert.same('this is ==probably== fine', line())
    inline.toggle('soft')
    assert.same('this is probably fine', line())
  end)

  it('keeps punctuation and hyphenated words intact', function()
    buffer('restart auth-svc, then (retry).', 10)
    inline.toggle('literal')
    assert.same('restart `auth-svc`, then (retry).', line())
    vim.api.nvim_win_set_cursor(0, { 1, 26 })
    inline.toggle('literal')
    assert.same('restart `auth-svc`, then (`retry`).', line())
  end)

  it('removes a multi-word span from anywhere inside it', function()
    buffer('key: ==do not merge== today', 12)
    inline.toggle('soft')
    assert.same('key: do not merge today', line())
  end)

  it('toggles case for strong', function()
    buffer('deploy is blocked now', 11)
    inline.toggle('strong')
    assert.same('deploy is BLOCKED now', line())
    inline.toggle('strong')
    assert.same('deploy is blocked now', line())
  end)

  it('only unwraps == pairs that form one span', function()
    buffer('x==y and z==w', 5)
    inline.toggle('soft')
    assert.same('x==y ==and== z==w', line())

    buffer('a==b', 0)
    inline.toggle('soft')
    assert.same('==a==b==', line())
    inline.toggle('soft')
    assert.same('a==b', line())
  end)

  it('keeps other markers outside a new span', function()
    buffer('==do not merge== now', 10)
    inline.toggle('literal')
    assert.same('==do not `merge`== now', line())
  end)

  it('uppercases non-ASCII letters', function()
    buffer('café', 0)
    inline.toggle('strong')
    assert.same('CAFÉ', line())
  end)

  it('does nothing on whitespace', function()
    buffer('a  b', 1)
    inline.toggle('soft')
    assert.same('a  b', line())
  end)
end)

describe('inline.toggle in visual mode', function()
  it('wraps and unwraps a selection', function()
    buffer('do not merge on friday', 0)
    toggle_selection('soft', 0, 12)
    assert.same('==do not merge== on friday', line())
    toggle_selection('soft', 2, 12)
    assert.same('do not merge on friday', line())
  end)

  it('uppercases a selection, then lowercases it', function()
    buffer('do not merge', 0)
    toggle_selection('strong', 0, 12)
    assert.same('DO NOT MERGE', line())
    toggle_selection('strong', 0, 12)
    assert.same('do not merge', line())
  end)

  it('handles v$ selecting past the end of the line', function()
    buffer('wrap all of this', 0)
    vim.cmd('normal! v$')
    inline.toggle('literal')
    assert.same('`wrap all of this`', line())
  end)

  it('handles multibyte characters at the end of a selection', function()
    buffer('say café now', 0)
    toggle_selection('literal', 4, 4)
    assert.same('say `café` now', line())
  end)
end)
