local list = require('rowan.list')
local parse = require('rowan.parse')

local function buffer(lines, lnum)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.api.nvim_win_set_cursor(0, { lnum or 1, 0 })
end

local function lines()
  return vim.api.nvim_buf_get_lines(0, 0, -1, false)
end

describe('parse.list_item', function()
  it('parses bullets and tasks', function()
    assert.same({ indent = '  ', marker = '*', text = 'x' }, parse.list_item('  * x'))
    assert.same({ indent = '', task = '>', text = 'later' }, parse.list_item('[>] later'))
    assert.is_nil(parse.list_item('-- H3 ---'))
    assert.is_nil(parse.list_item('plain'))
  end)
end)

describe('tasks', function()
  it('cycles plain > [ ] > [x] > [ ]', function()
    buffer({ '  rotate keys' })
    list.task_cycle()
    assert.same({ '  [ ] rotate keys' }, lines())
    list.task_cycle()
    assert.same({ '  [x] rotate keys' }, lines())
    list.task_cycle()
    assert.same({ '  [ ] rotate keys' }, lines())
  end)

  it('turns a bullet into a task', function()
    buffer({ '- ship it' })
    list.task_cycle()
    assert.same({ '[ ] ship it' }, lines())
  end)

  it('marks moved and back', function()
    buffer({ '[ ] review' })
    list.task_moved()
    assert.same({ '[>] review' }, lines())
    list.task_moved()
    assert.same({ '[ ] review' }, lines())
    list.task_moved()
    list.task_cycle()
    assert.same({ '[ ] review' }, lines())
  end)

  it('leaves headings, rules and dividers alone', function()
    local untouched = { '== H2 =====', '-- H3 -----', ('='):rep(10), ('-'):rep(10) }
    buffer(vim.deepcopy(untouched))
    vim.cmd('normal! VG')
    list.task_cycle()
    assert.same(untouched, lines())
  end)

  it('keeps a single checkbox when a bullet already holds one', function()
    buffer({ '- [ ] mixed' })
    list.task_cycle()
    assert.same({ '[ ] mixed' }, lines())
  end)

  it('leaves blank lines alone', function()
    buffer({ '', '   ' })
    list.task_cycle()
    assert.same({ '', '   ' }, lines())
  end)

  it('applies to a visual selection', function()
    buffer({ 'a', 'b', 'c' })
    vim.cmd('normal! Vj')
    list.task_cycle()
    assert.same({ '[ ] a', '[ ] b', 'c' }, lines())
  end)
end)
