local keymaps = require('rowan.keymaps')
local list = require('rowan.list')
local parse = require('rowan.parse')

local function buffer(lines, lnum)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_current_buf(buf)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.api.nvim_win_set_cursor(0, { lnum or 1, 0 })
  vim.bo.shiftwidth = 2
  vim.bo.expandtab = true
  vim.bo.softtabstop = 2
  vim.bo.autoindent = true
  keymaps.apply(buf)
end

local function type(keys)
  vim.api.nvim_feedkeys(vim.keycode(keys), 'xt', false)
end

local function lines()
  return vim.api.nvim_buf_get_lines(0, 0, -1, false)
end

describe('parse.list_item', function()
  it('parses bullets and tasks', function()
    assert.same({ indent = '  ', marker = '*', text = 'x' }, parse.list_item('  * x'))
    assert.same({ indent = '', task = '>', text = 'later' }, parse.list_item('[>] later'))
    assert.is_nil(parse.list_item('-- H3 ---'))
    assert.is_nil(parse.list_item('plain'))
  end)
end)

describe('tasks', function()
  it('cycles plain > [ ] > [x] > [ ]', function()
    buffer({ '  rotate keys' })
    list.task_cycle()
    assert.same({ '  [ ] rotate keys' }, lines())
    list.task_cycle()
    assert.same({ '  [x] rotate keys' }, lines())
    list.task_cycle()
    assert.same({ '  [ ] rotate keys' }, lines())
  end)

  it('turns a bullet into a task', function()
    buffer({ '- ship it' })
    list.task_cycle()
    assert.same({ '[ ] ship it' }, lines())
  end)

  it('marks moved and back', function()
    buffer({ '[ ] review' })
    list.task_moved()
    assert.same({ '[>] review' }, lines())
    list.task_moved()
    assert.same({ '[ ] review' }, lines())
    list.task_moved()
    list.task_cycle()
    assert.same({ '[ ] review' }, lines())
  end)

  it('leaves headings, rules and dividers alone', function()
    local untouched = { '== H2 =====', '-- H3 -----', ('='):rep(10), ('-'):rep(10) }
    buffer(vim.deepcopy(untouched))
    vim.cmd('normal! VG')
    list.task_cycle()
    assert.same(untouched, lines())
  end)

  it('keeps a single checkbox when a bullet already holds one', function()
    buffer({ '- [ ] mixed' })
    list.task_cycle()
    assert.same({ '[ ] mixed' }, lines())
  end)

  it('leaves blank lines alone', function()
    buffer({ '', '   ' })
    list.task_cycle()
    assert.same({ '', '   ' }, lines())
  end)

  it('applies to a visual selection', function()
    buffer({ 'a', 'b', 'c' })
    vim.cmd('normal! Vj')
    list.task_cycle()
    assert.same({ '[ ] a', '[ ] b', 'c' }, lines())
  end)
end)

describe('typing lists', function()
  it('continues bullets and tasks on Enter', function()
    buffer({ '  * one', '[x] done' })
    type('A<CR>two<Esc>jA<CR>next<Esc>')
    assert.same({ '  * one', '  * two', '[x] done', '[ ] next' }, lines())
  end)

  it('ends the list on an empty item', function()
    buffer({ '- one' })
    type('A<CR><CR>after<Esc>')
    assert.same({ '- one', 'after' }, lines())
  end)

  it('splits an item when Enter is pressed mid-text', function()
    buffer({ '- one two' })
    type('0fti<CR><Esc>')
    assert.same({ '- one ', '- two' }, lines())
  end)

  it('leaves Enter alone on plain lines and before the marker', function()
    buffer({ 'plain', '- item' })
    type('A<CR>x<Esc>jI<CR><Esc>')
    assert.same({ 'plain', 'x', '', '- item' }, lines())
  end)

  it('nests and un-nests with Tab and S-Tab, changing the marker', function()
    buffer({ '- item' })
    type('A<Tab><Esc>')
    assert.same({ '  * item' }, lines())
    type('A<Tab><Esc>')
    assert.same({ '    + item' }, lines())
    type('A<S-Tab><S-Tab><S-Tab><Esc>')
    assert.same({ '- item' }, lines())
  end)

  it('snaps odd indents onto the shiftwidth grid', function()
    buffer({ '   - odd' })
    type('A<Tab><Esc>')
    assert.same({ '    + odd' }, lines())
    type('A<S-Tab><Esc>')
    assert.same({ '  * odd' }, lines())
  end)

  it('keeps the checkbox when nesting a task', function()
    buffer({ '[ ] task' })
    type('A<Tab>!<Esc>')
    assert.same({ '  [ ] task!' }, lines())
  end)

  it('keeps Tab as a Tab on plain lines', function()
    buffer({ 'a' })
    type('A<Tab>b<Esc>')
    assert.same({ 'a b' }, lines())
  end)
end)
